"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATIC_ROOT =   os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
# Default file storage configuratio
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2qp%sfmoj@77se4d_#-t_2@e6-e6)8@(!$fm&#-rm5vw4%7@)i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 

ALLOWED_HOSTS = [   
    "127.0.0.1",
    "localhost", 
    "104.248.186.90",
    "budget.rewildingchile.org",
    "app.rewildingchile.org"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'maestros',
    'presupuestos',
    'libromayor'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
CORS_ALLOWED_ORIGINS = [
        "https://budget.rewildingchile.org",
        "https://app.rewildingchile.org",
]
MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 👈 soporte español
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = { 
      'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'presupuestos_v2',  
        'USER': 'presupuestos',                 
        'PASSWORD': '@Centenario1705!',          
        'HOST': 'localhost',                
        'PORT': '5432',                     
    } 
}
#presupbackp


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es' 
TIME_ZONE = 'America/Santiago'
USE_I18N = True #Activa el sistema de traducciones de Django.
USE_L10N = True #Controla formatos locales: fechas, numeros, monedas
USE_TZ = True #Activa manejo de zonas horarias.
 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    # Duración del token de acceso (usado en cada request)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    # Duración del token de refresco (para pedir nuevos access tokens)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7)
}    

 

MESES = ["", "Ene.",
        "Febre",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agost",
        "Sept.",
        "Oct.",
        "Nov.",
        "Dic.",]

ID_CTA_REMUNERACIONES=1