# Generated by Django 5.2.7 on 2026-06-23 14:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único en tu BD.', primary_key=True, serialize=False)),
                ('drive_file_id', models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='El nombre del archivo o carpeta.', max_length=255)),
                ('mime_type', models.CharField(help_text='El tipo MIME de Google (application/vnd.google-apps.folder para carpetas).', max_length=255)),
                ('drive_web_view_link', models.URLField(blank=True, help_text='Enlace público para vista/previsualización.', max_length=500, null=True)),
                ('last_known_modified_time', models.DateTimeField(help_text='Última fecha de modificación conocida en Drive. Esencial para detectar cambios.', null=True)),
                ('last_synced_at', models.DateTimeField(help_text='Marca de tiempo de la última sincronización con Google Drive.', null=True)),
                ('area', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='googledrive.area')),
                ('parent_drive_file_id', models.ForeignKey(blank=True, db_column='parent_drive_file_id', help_text='ID de la carpeta que lo contiene (para mapear la jerarquía).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='googledrive.googledrivefile', to_field='drive_file_id')),
            ],
            options={
                'verbose_name': 'Archivo de Google Drive',
                'verbose_name_plural': 'Archivos de Google Drive',
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('file', models.OneToOneField(db_column='drive_file_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='googledrive.googledrivefile', to_field='drive_file_id')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page_token', models.CharField(max_length=255)),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googledrive.area')),
            ],
        ),
        migrations.AddIndex(
            model_name='googledrivefile',
            index=models.Index(fields=['drive_file_id'], name='googledrive_drive_f_ec16fa_idx'),
        ),
        migrations.AddIndex(
            model_name='googledrivefile',
            index=models.Index(fields=['parent_drive_file_id'], name='googledrive_parent__6f275f_idx'),
        ),
        migrations.AddIndex(
            model_name='googledrivefile',
            index=models.Index(fields=['last_known_modified_time'], name='googledrive_last_kn_53d877_idx'),
        ),
        migrations.AddIndex(
            model_name='googledrivefiledocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='googledrive_search__f73003_gin'),
        ),
    ]
