# Generated by Django 5.2.7 on 2026-05-12 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único en tu BD.', primary_key=True, serialize=False)),
                ('drive_file_id', models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, unique=True)),
                ('name', models.CharField(help_text='El nombre del archivo o carpeta.', max_length=255)),
                ('mime_type', models.CharField(help_text='El tipo MIME de Google (application/vnd.google-apps.folder para carpetas).', max_length=255)),
                ('drive_web_view_link', models.URLField(blank=True, help_text='Enlace público para vista/previsualización.', max_length=500, null=True)),
                ('last_known_modified_time', models.DateTimeField(help_text='Última fecha de modificación conocida en Drive. Esencial para detectar cambios.')),
                ('last_synced_at', models.DateTimeField(help_text='Marca de tiempo de la última sincronización con Google Drive.')),
                ('area', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='googledrive.area')),
                ('parent_drive_file_id', models.ForeignKey(blank=True, db_column='parent_drive_file_id', help_text='ID de la carpeta que lo contiene (para mapear la jerarquía).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='googledrive.googledrivefile', to_field='drive_file_id')),
            ],
            options={
                'verbose_name': 'Archivo de Google Drive',
                'verbose_name_plural': 'Archivos de Google Drive',
                'indexes': [models.Index(fields=['drive_file_id'], name='googledrive_drive_f_ec16fa_idx'), models.Index(fields=['parent_drive_file_id'], name='googledrive_parent__6f275f_idx'), models.Index(fields=['last_known_modified_time'], name='googledrive_last_kn_53d877_idx')],
            },
        ),
    ]
