# Generated by Django 5.2.7 on 2026-06-23 14:59

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivefiledocument',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='googledrivefiledocument',
            name='description_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
