# Generated by Django 5.2.7 on 2026-07-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0002_googledrivefiledocument_description_and_more'),
        ('maestros', '0003_area_areausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivefile',
            name='area',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.area'),
        ),
        migrations.AlterField(
            model_name='googledrivesyncstate',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maestros.area'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
