# Generated by Django 5.2.7 on 2026-05-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0002_rename_googledrivefile_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='GoogleDriveFile',
        ),
        migrations.RenameIndex(
            model_name='googledrivefile',
            new_name='googledrive_drive_f_ec16fa_idx',
            old_name='googledrive_drive_f_8c05dc_idx',
        ),
        migrations.RenameIndex(
            model_name='googledrivefile',
            new_name='googledrive_parent__6f275f_idx',
            old_name='googledrive_parent__3f2f5f_idx',
        ),
        migrations.RenameIndex(
            model_name='googledrivefile',
            new_name='googledrive_last_kn_53d877_idx',
            old_name='googledrive_last_kn_8760b1_idx',
        ),
    ]
