# Generated by Django 5.2.7 on 2026-05-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0003_rename_file_googledrivefile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page_token', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googledrive.area')),
            ],
        ),
    ]
