# Generated by Django 5.2.7 on 2026-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0004_googledrivefile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivefile',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
