# Generated by Django 5.2.7 on 2026-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0004_googledrivesyncstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivesyncstate',
            name='last_full_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
