# Generated by Django 5.2.7 on 2026-08-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='googledrivefile',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, help_text='Tamaño del archivo en bytes (solo para archivos, null para carpetas).', null=True),
        ),
    ]
