# Generated by Django 5.2.7 on 2026-05-20 16:51

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivesyncstate_last_full_sync_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googledrivefile',
            name='last_known_modified_time',
            field=models.DateTimeField(help_text='Última fecha de modificación conocida en Drive. Esencial para detectar cambios.', null=True),
        ),
        migrations.AlterField(
            model_name='googledrivefile',
            name='last_synced_at',
            field=models.DateTimeField(help_text='Marca de tiempo de la última sincronización con Google Drive.', null=True),
        ),
        migrations.CreateModel(
            name='GoogleDriveFileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(unique=True)),
                ('text_content', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='googledrive_search__f73003_gin')],
            },
        ),
    ]
