# Generated by Django 5.2.7 on 2026-05-26 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0006_alter_googledrivefile_last_known_modified_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googledrivefiledocument',
            name='file_id',
        ),
        migrations.AddField(
            model_name='googledrivefiledocument',
            name='file',
            field=models.OneToOneField(db_column='drive_file_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
        migrations.AlterField(
            model_name='googledrivefiledocument',
            name='text_content',
            field=models.TextField(null=True),
        ),
    ]
