# Generated by Django 5.2.7 on 2026-05-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0007_remove_googledrivefiledocument_file_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='googledrivefile',
            name='googledrive_parent__6f275f_idx',
        ),
        migrations.RenameField(
            model_name='googledrivefile',
            old_name='parent_drive_file_id',
            new_name='parent',
        ),
        migrations.AddIndex(
            model_name='googledrivefile',
            index=models.Index(fields=['parent'], name='googledrive_parent__6f275f_idx'),
        ),
    ]
