# Generated by Django 5.2.7 on 2026-07-21 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_area_areausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaUsuario',
            new_name='UsuarioArea',
        ),
    ]
