# Generated by Django 5.2.7 on 2026-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_rename_areausuario_usuarioarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='drive_web_view_link',
            field=models.URLField(blank=True, help_text='folder id google', max_length=500, null=True),
        ),
    ]
