# Generated by Django 5.2.7 on 2026-07-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_area_drive_web_view_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='drive_web_view_link',
            field=models.CharField(blank=True, help_text='folder id google', max_length=500, null=True),
        ),
    ]
