# Generated by Django 5.2.7 on 2026-07-21 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_alter_area_drive_web_view_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='drive_web_view_link',
            new_name='drive_folder_id',
        ),
    ]
