# Generated by Django 5.2.7 on 2026-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_rename_drive_web_view_link_area_drive_folder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='drive_folder_id',
            new_name='biblioteca_folder_id',
        ),
        migrations.AddField(
            model_name='area',
            name='temporal_folder_id',
            field=models.CharField(blank=True, help_text='folder id google', max_length=500, null=True),
        ),
    ]
