# Generated by Django 5.2.7 on 2026-07-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_rename_drive_folder_id_area_biblioteca_folder_id_and_more'),
        ('solicitudes', '0004_rename_accion_userrequest_type_action_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='TypeActionRequest',
        ),
    ]
