# Generated by Django 5.2.7 on 2026-07-14 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0002_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSolicitude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único en tu BD.', primary_key=True, serialize=False)),
                ('drive_file_id', models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, unique=True)),
                ('temp_file_id', models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, unique=True)),
                ('new_name', models.CharField(help_text='El nombre del archivo o carpeta.', max_length=255)),
                ('accion', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.action')),
                ('destination_drive_parent_drive_file_id', models.ForeignKey(blank=True, db_column='parent_drive_file_id', help_text='ID de la carpeta que lo contiene (para mapear la jerarquía).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='solicitudes.usersolicitude', to_field='drive_file_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
