# Generated by Django 5.2.7 on 2026-07-21 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_rename_areausuario_usuarioarea'),
        ('solicitudes', '0002_rename_usersolicitude_userrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.area'),
        ),
    ]
