# Generated by Django 5.2.7 on 2026-07-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_userrequest_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='accion',
            new_name='type_action_request',
        ),
    ]
