# Generated by Django 5.2.7 on 2026-07-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_rename_accion_userrequest_type_action_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='destination_drive_parent_drive_file_id',
            new_name='parent_drive_file_id',
        ),
    ]
