# Generated by Django 5.2.7 on 2026-07-27 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_rol_usuarioarea_rol'),
        ('solicitudes', '0005_rename_destination_drive_parent_drive_file_id_userrequest_parent_drive_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='type_action_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maestros.typeactionrequest'),
        ),
    ]
