# Generated by Django 5.2.7 on 2026-07-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_userrequest_type_action_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='drive_web_view_link',
            field=models.URLField(blank=True, help_text='Enlace público para vista/previsualización.', max_length=500, null=True),
        ),
    ]
