# Generated by Django 5.2.7 on 2026-07-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_userrequest_drive_web_view_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='last_synced_at',
            field=models.DateTimeField(help_text='Marca de tiempo de la última sincronización con Google Drive.', null=True),
        ),
    ]
