# Generated by Django 5.2.7 on 2026-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_userrequest_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='mime_type',
            field=models.CharField(blank=True, help_text='El tipo MIME de Google (application/vnd.google-apps.folder para carpetas).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='name',
            field=models.CharField(help_text='El nombre del archivo o carpeta.', max_length=255, null=True),
        ),
    ]
