# Generated by Django 5.2.7 on 2026-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_userrequest_mime_type_userrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='parent_drive_file_id',
            field=models.CharField(blank=True, help_text='carpeta que aloja el archivo', max_length=255, null=True),
        ),
    ]
