# Generated by Django 5.2.7 on 2026-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_alter_userrequest_parent_drive_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='temp_file_id',
            field=models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255),
        ),
    ]
