# Generated by Django 5.2.7 on 2026-07-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_alter_userrequest_temp_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='parent_drive_file_id',
            new_name='folder_final_id',
        ),
        migrations.RenameField(
            model_name='userrequest',
            old_name='temp_file_id',
            new_name='folder_origin_id',
        ),
    ]
