# Generated by Django 5.2.7 on 2026-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_rename_parent_drive_file_id_userrequest_folder_final_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='pendiente',
            field=models.BooleanField(default=True),
        ),
    ]
