# Generated by Django 5.2.7 on 2026-07-30 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('maestros', '0010_rol_usuarioarea_rol'),
        ('solicitudes', '0013_userrequest_pendiente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='folder_origin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['folder_origin_id'], name='folder_origin_idx'),
        ),
    ]
