# Generated by Django 5.2.7 on 2026-07-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_alter_userrequest_folder_origin_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='folder_origin_id',
            new_name='folder_origin',
        ),
    ]
