# Generated by Django 5.2.7 on 2026-07-30 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('maestros', '0010_rol_usuarioarea_rol'),
        ('solicitudes', '0015_rename_folder_origin_id_userrequest_folder_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrequest',
            name='folder_origin_idx',
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['folder_origin'], name='folder_origin_idx'),
        ),
    ]
