# Generated by Django 5.2.7 on 2026-07-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0017_remove_userrequest_folder_origin_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='drive_file_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_file', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='folder_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_origin', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
