# Generated by Django 5.2.7 on 2026-07-30 14:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('maestros', '0010_rol_usuarioarea_rol'),
        ('solicitudes', '0018_alter_userrequest_drive_file_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='drive_file_id',
            new_name='drive_file',
        ),
        migrations.AddIndex(
            model_name='userrequest',
            index=models.Index(fields=['drive_file'], name='drive_file_idx', opclasses=['varchar_pattern_ops']),
        ),
    ]
