# Generated by Django 5.2.7 on 2026-07-30 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0020_rename_drive_file_idx_drive_fileid_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userrequest',
            new_name='drive_file_idx',
            old_name='drive_fileid_idx',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='drive_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_file', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
