# Generated by Django 5.2.7 on 2026-07-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0021_rename_drive_fileid_idx_drive_file_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrequest',
            name='drive_file_idx',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='drive_file',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='folder_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
