# Generated by Django 5.2.7 on 2026-07-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0022_remove_userrequest_drive_file_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userrequest',
            name='folder_origin_idx',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='folder_origin',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='folder_origin_id',
            field=models.CharField(blank=True, help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='drive_file_id',
            field=models.CharField(help_text='ID único que Google asigna al archivo o carpeta.', max_length=255, null=True, unique=True),
        ),
    ]
