# Generated by Django 5.2.7 on 2026-07-30 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0024_userrequest_googledrivefile_folder_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='googledrivefile_folder_origin',
            field=models.ForeignKey(blank=True, db_column='googledrivefile_folder_origin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_origin_id', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
