# Generated by Django 5.2.7 on 2026-07-30 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0025_alter_userrequest_googledrivefile_folder_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='googledrivefile_drive_file',
            field=models.ForeignKey(blank=True, db_column='googledrivefile_drive_file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_fileid', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
