# Generated by Django 5.2.7 on 2026-07-30 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googledrive', '0005_googledrivefile_hidden'),
        ('solicitudes', '0026_userrequest_googledrivefile_drive_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='googledrivefile_folder_final',
            field=models.ForeignKey(blank=True, db_column='googledrivefile_folder_final', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drive_folderfinal', to='googledrive.googledrivefile', to_field='drive_file_id'),
        ),
    ]
