# Generated by Django 5.2.7 on 2026-08-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0027_userrequest_googledrivefile_folder_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='new_name',
            field=models.CharField(blank=True, help_text='El nombre del archivo o carpeta.', max_length=255, null=True),
        ),
    ]
