# Generated by Django 5.2.7 on 2026-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0028_alter_userrequest_new_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
    ]
